### ISSUE TITLE
Why not a Time?

### ISSUE THREAD

**Issue by BrianHicks** [elm-lang/geolocation#9]
The timeout and TTL are specified using plain integer values. The docs specify a unit (yay!), but Time encodes it in a type. Is there some design constraint that makes Time undesirable here?

**Comment by evancz** [comment]
Can you add some code or links so I know what you are referring to? Just edit the initial comment and ping me in some other channel when you add that info.

**Comment by evancz** [comment]
Actually, let's just do a new issue that has the necessary context.
